server:
  forward-headers-strategy: framework
  servlet:
    context-path: /
  port:
    8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/Gayrat
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:dev}
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
          id: document-service
          uri: lb://document-service
          predicates[0]: Path=/api/document


      routes[1]:
        uri: lb://employee-service
        id: employee-service
        predicates[0]: Path=/api/employee

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /employee-service/v3/api-docs
        name: Employee Service
        primaryName: Employee Service
      - url: /document-service/v3/api-docs
        name: Document Service
        primaryName: Document Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
jwt:
  auth:
    converter:
      resource-id: hr-rest-api
      principle-attribute: preferred_username
