server:
  port: 8083
spring:
  application:
    name: user-service
keycloak:
  auth-server-url: http://localhost:8090
  realm: Gayrat
  resource: hr-rest-api
  credentials:
    secret: a2zeWIx87DUFam3GbyCLKbmGr493Dbdf
